version: "3.7"
services:

  database:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    user: root
    volumes:
      - ./backup_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    depends_on:
      - database
  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - 80:80

  do-migration:
    build: ./backend
    depends_on:
      - backend
    command:
      - /bin/bash
      - -c
      - |
        echo "Apply migration"
        python manage.py makemigrations
        python manage.py migrate
        exit 0
    volumes:
      - ./backend:/app
  
  nginx_backend_server:
    build: ./nginx_backend_server
    restart: always
    ports:
        - 8000:8000
    depends_on:
        - backend